const categories = [
  { name: "Marlite Panels (FED)" },
  { name: "HVAC" },
  { name: "Ornamental Railings" },
  { name: "Fire Sprinkler System" },
  { name: "Drywall & Acoustical (MOB)" },
  { name: "Masonry & Precast" },
  { name: "Drywall & Acoustical (FED)" },
  { name: "Structural and Misc Steel (Fabrication)" },
  { name: "Structural & Misc Steel Erection" },
  { name: "Soft Flooring and Base" },
  { name: "Electrical" },
  { name: "Glass & Glazing" },
  { name: "Sitework & Site Utilities" },
  { name: "Structural & Misc Steel Erection" },
  { name: "Structural & Misc Steel Erection" },
  { name: "Site Furnishings" },
  { name: "Hard Tile & Stone" },
  { name: "Electrical and Fire Alarm" },
  { name: "Rebar & Wire Mesh Install" },
  { name: "Fire Protection" },
  { name: "Electrical" },
  { name: "Casework" },
  { name: "Doors, Frames & Hardware" },
  { name: "Landscaping & Irrigation" },
  { name: "Framing (Wood)" },
  { name: "Ornamental Railings" },
  { name: "Curb & Gutter" },
  { name: "Rebar & Wire Mesh Install" },
  { name: "Glass & Glazing" },
  { name: "Drywall & Acoustical (FED)" },
  { name: "HVAC" },
  { name: "Temp Fencing, Decorative Fencing and Gates" },
  { name: "Framing (Steel)" },
  { name: "Framing (Steel)" },
  { name: "Masonry & Precast" },
  { name: "RF Shielding" },
  { name: "Framing (Steel)" },
  { name: "Fire Protection" },
  { name: "Retaining Wall and Brick Pavers" },
  { name: "Sitework & Site Utilities" },
  { name: "Site Furnishings" },
  { name: "Structural and Misc Steel (Fabrication)" },
  { name: "Overhead Doors" },
  { name: "Landscaping & Irrigation" },
  { name: "Electrical" },
  { name: "Sitework & Site Utilities" },
  { name: "Sitework & Site Utilities" },
  { name: "Landscaping & Irrigation" },
  { name: "Casework" },
  { name: "Framing (Steel)" },
  { name: "Granite Surfaces" },
  { name: "Structural & Misc Steel Erection" },
  { name: "Structural & Misc Steel Erection" },
  { name: "Painting & Vinyl Wall Covering" },
  { name: "HVAC" },
  { name: "EIFS" },
  { name: "Asphalt Paving" },
  { name: "Elevator" },
  { name: "RF Shielding" },
  { name: "Masonry" },
  { name: "Plumbing & Medical Gas" },
  { name: "Plumbing & Medical Gas" },
  { name: "Prefabricated Aluminum Metal Canopies" },
  { name: "Framing (Wood)" },
  { name: "Framing (Wood)" },
  { name: "Fire Protection" },
  { name: "Roofing (Metal)" },
  { name: "Rebar & Wire Mesh Install" },
  { name: "Sitework & Site Utilities" },
  { name: "Overhead Doors" },
  { name: "Roofing (Asphalt)" },
  { name: "Fire Sprinkler System" },
  { name: "Drywall & Acoustical (FED)" },
  { name: "Retaining Wall and Brick Pavers" },
  { name: "Temp Fencing, Decorative Fencing and Gates" },
  { name: "Roofing (Metal)" },
  { name: "Structural and Misc Steel (Fabrication)" },
  { name: "Retaining Wall and Brick Pavers" },
  { name: "RF Shielding" },
  { name: "Retaining Wall and Brick Pavers" },
  { name: "Epoxy Flooring" },
  { name: "Painting & Vinyl Wall Covering" },
  { name: "Glass & Glazing" },
  { name: "Marlite Panels (FED)" },
  { name: "Plumbing & Medical Gas" },
  { name: "Roofing (Asphalt)" },
  { name: "Site Furnishings" },
  { name: "Fire Sprinkler System" },
  { name: "Hard Tile & Stone" },
  { name: "Roofing (Metal)" },
  { name: "Electrical and Fire Alarm" },
  { name: "Masonry & Precast" },
  { name: "Asphalt Paving" },
  { name: "Ornamental Railings" },
  { name: "Electrical and Fire Alarm" },
  { name: "HVAC" },
  { name: "Marlite Panels (FED)" },
  { name: "Soft Flooring and Base" },
  { name: "Ornamental Railings" },
  { name: "Termite Control" },
];

export default categories;
